### ISSUE TITLE
`duration` is not included in the default row format

### ISSUE THREAD

**Issue by noelspringer** [atheriel/org-clock-csv#16]
## Question

The default `org-clock-csv-header` list does not include `duration` by default and nor is it in the `org-clock-csv-default-row-fmt`.

I tried adding these and yes it prints out `duration` in the header list but adding `(plist-get plist ':duration)` to the `org-clock-csv-default-row-fmt` has no effect.

How can I add the `duration` value to the row output?

**Comment by atheriel** [comment]
Duration is not included by default because (1) it's redundant, and (2) possible incorrect.

However, it is *absolutely* possible to include it by implementing your own formatting function: you can see an example that does this in [the test suite](https://github.com/atheriel/org-clock-csv/blob/ab6021310a6af53f84e56bef92b41979b40c0bee/org-clock-csv-tests.el#L31).
