### ISSUE TITLE
Export from current file with prefix argument

### ISSUE THREAD

**Issue by quazgar** [atheriel/org-clock-csv#17]
## Enhancement proposal
When called with an empty argument `C-u M-x org-clock-csv`, the functyion should parse just the visited buffer.  This would act as a shortcut instead of writing out the full file name.

**Comment by atheriel** [comment]
This sounds like a reasonable approach, as long as it does not interfere with other features. We would have to do some things like check if the current buffer is an org one, though.

**Comment by quazgar** [comment]
Thanks, that was great and quick!  And it works for me now.

**Comment by atheriel** [comment]
Just happened to have some time to work on the package today. Glad you like it.

**Comment by GCamp6** [comment]
Hi, I'm using org-journal and I clock my activities on that file but it has no `.org` extension even though it is written as an org-mode buffer. Is it possible to overcome this limitation and run `org-clock-csv` on this buffer too?


**EDIT: _I realized I can switch back and forth between `org-mode` and `org-journal-mode` in the journal buffer so that it is recognized as org-mode buffer and `org-clock-csv` can be invoked_**
